# Generated by Django 5.1.1 on 2024-10-28 17:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_extract_registro', models.DateField()),
                ('nombre_tecnico', models.CharField(max_length=100)),
                ('nombre_team', models.CharField(max_length=100)),
                ('especialidad_usuario', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('rut_tecnico', models.CharField(max_length=12)),
                ('zona_operacional', models.CharField(max_length=100)),
                ('zona_adjudicacion', models.CharField(max_length=100)),
                ('especialidad_team', models.CharField(max_length=100)),
                ('capacidad', models.FloatField()),
                ('total_hh', models.FloatField()),
                ('phi', models.FloatField(blank=True, null=True)),
                ('total_hh_phi', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FechaExtractRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tecnico', models.CharField(max_length=100)),
                ('fecha_extract_registro', models.DateField()),
                ('nombre_team', models.CharField(max_length=100)),
                ('especialidad_usuario', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('rut_tecnico', models.CharField(max_length=100)),
                ('zona_operacional', models.CharField(max_length=100)),
                ('zona_adjudicacion', models.CharField(max_length=100)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hh_phi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_pago', models.CharField(default='2024-01', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='LPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_tarea', models.CharField(max_length=255)),
                ('tipo_red', models.CharField(max_length=255)),
                ('tipo_red_2', models.CharField(blank=True, max_length=255, null=True)),
                ('area_empresa', models.CharField(max_length=255)),
                ('zona_adjudicacion', models.CharField(max_length=255)),
                ('zona_operativa', models.CharField(max_length=255)),
                ('zona_cluster', models.CharField(max_length=255)),
                ('estado_de_trabajo', models.CharField(max_length=255)),
                ('sap_fijo_lpu', models.CharField(max_length=255)),
                ('sap_capex_lpu', models.CharField(max_length=255)),
                ('sap_opex_lpu', models.CharField(max_length=255)),
                ('item_lpu', models.CharField(max_length=255)),
                ('precio_mdm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicios', models.CharField(max_length=255)),
                ('factor_multiplicador', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_presupuesto', models.CharField(max_length=255)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_finalizacion_tarea', models.DateTimeField(blank=True, null=True)),
                ('fecha_ingreso_trans_sap', models.DateTimeField(blank=True, null=True)),
                ('tiempo_trans_sap', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_ingreso_validar_trans_sap', models.DateTimeField(blank=True, null=True)),
                ('tiempo_validar_trans_sap', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_final', models.DateTimeField(blank=True, null=True)),
                ('nombre_de_proyecto', models.CharField(max_length=255)),
                ('ano_finalizacion', models.IntegerField()),
                ('mes_finalizacion', models.IntegerField()),
                ('observacion_1', models.TextField(blank=True, null=True)),
                ('observacion_2', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NombreTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NuevaTablaPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sociedad', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('especialidad', models.CharField(max_length=255)),
                ('zona_adjudicacion', models.CharField(max_length=255)),
                ('zona_operacional', models.CharField(max_length=255)),
                ('nuevo_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desvio_porcentaje', models.DecimalField(decimal_places=4, max_digits=5)),
                ('area', models.CharField(max_length=255)),
                ('anio', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=255)),
                ('especialidad', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('gastos_administrativos', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('lpu', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sla', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('vehiculo', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_general', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='SLAReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_adjudicacion', models.CharField(max_length=255)),
                ('zona_operativa', models.CharField(max_length=255)),
                ('bonus_o_malus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proyecto', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TablaDePagoCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tecnico', models.CharField(max_length=255)),
                ('nombre_team', models.CharField(max_length=255)),
                ('especialidad_usuario', models.CharField(max_length=255)),
                ('rut_tecnico', models.CharField(max_length=12)),
                ('zona_operacional', models.CharField(max_length=255)),
                ('zona_adjudicacion', models.CharField(max_length=255)),
                ('total_hh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_hh_phi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nuevo_precio_2024', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Q', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_a_Pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_red', models.CharField(max_length=50)),
                ('proyecto', models.CharField(max_length=255)),
                ('tipo_especialidad', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaAdjudicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name_paterno', models.CharField(max_length=30)),
                ('last_name_materno', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PrecioEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sociedad', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('especialidad', models.CharField(max_length=255)),
                ('zona_adjudicacion', models.CharField(max_length=255)),
                ('zona_operacional', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desvio_porcentaje', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
            options={
                'unique_together': {('especialidad', 'zona_adjudicacion', 'zona_operacional', 'area', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.especialidadusuario')),
            ],
        ),
        migrations.CreateModel(
            name='NombreTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tecnicos', models.ManyToManyField(blank=True, to='pagos.tecnico')),
            ],
        ),
    ]
