# Generated by Django 5.1.1 on 2024-10-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabladepagocapacity',
            old_name='nuevo_precio_2024',
            new_name='nuevo_precio',
        ),
    ]
