# Generated by Django 5.1.1 on 2024-11-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_rename_observacion_1_lpu_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lpu',
            name='derivada_pago_septiembre',
        ),
        migrations.RemoveField(
            model_name='lpu',
            name='hem_pago_septiembre',
        ),
        migrations.RemoveField(
            model_name='lpu',
            name='monto_pagado_hem_septiembre',
        ),
        migrations.RemoveField(
            model_name='lpu',
            name='tipo_red_2',
        ),
        migrations.AddField(
            model_name='lpu',
            name='tipo_red2',
            field=models.CharField(default='FIJA', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lpu',
            name='area_empresa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lpu',
            name='fecha_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lpu',
            name='fecha_finalizacion_tarea',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lpu',
            name='fecha_ingreso_trans_sap',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lpu',
            name='fecha_ingreso_validar_trans_sap',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lpu',
            name='mes_finalizacion',
            field=models.CharField(max_length=3),
        ),
    ]
