# Generated by Django 5.1.1 on 2024-11-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_remove_lpu_derivada_pago_septiembre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabladepagocapacity',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
