# Generated by Django 5.1.1 on 2024-12-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_tabladepagocapacity_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionDePagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('nuevo_precio_2024', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
