# Generated by Django 5.1.1 on 2024-10-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpu',
            name='estado_presupuesto',
            field=models.CharField(default='pendiente', max_length=255),
        ),
        migrations.AddField(
            model_name='lpu',
            name='observacion_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lpu',
            name='observacion_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lpu',
            name='tipo_red2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
