# Generated by Django 5.1.1 on 2024-10-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_lpu_estado_presupuesto_lpu_observacion_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lpu',
            old_name='tipo_red2',
            new_name='tipo_red_2',
        ),
        migrations.AlterField(
            model_name='lpu',
            name='ano_finalizacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lpu',
            name='estado_presupuesto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lpu',
            name='factor_multiplicador',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lpu',
            name='mes_finalizacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lpu',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lpu',
            name='precio_mdm',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lpu',
            name='servicios',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lpu',
            name='tiempo_trans_sap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lpu',
            name='tiempo_validar_trans_sap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lpu',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
