# Generated by Django 5.1.1 on 2024-10-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_precioespecialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='precioespecialidad',
            name='desvio_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='precioespecialidad',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='precioespecialidad',
            name='sociedad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
