# Generated by Django 5.1.1 on 2024-10-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_precioespecialidad_desvio_porcentaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
        model_name='nuevatablapagos',
        old_name='nuevo_precio_2024',
        new_name='nuevo_precio',
    ),
    migrations.AddField(
        model_name='nuevatablapagos',
        name='anio',
        field=models.PositiveIntegerField(default=2024),
    ),
    ]
