# Generated by Django 5.1.1 on 2024-10-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevatablapagos',
            name='anio',
            field=models.PositiveIntegerField(),
        ),
    ]
