# Generated by Django 5.1.1 on 2024-10-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_slareport_fecha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZonaOperacional',
            new_name='ZonaOperativa',
        ),
        migrations.AlterModelOptions(
            name='zonaoperativa',
            options={'verbose_name': 'Zona Operativa', 'verbose_name_plural': 'Zonas Operativas'},
        ),
    ]
